### ISSUE TITLE
JW Library versión 14.0 breaks merging

### ISSUE THREAD

**Issue by ajw-dev** [AndreasSko/ios-jwlm#57]
After having updated my devices to JW Library, version 14.0, I can no longer use the Library Merge app to merge my data. I get an error when trying to select a Library backup created with the updated JW Library. The error states:

“Schema version is incompatible. Should be 8 is 13. You might need to upgrade to a newer version of JW Library first”

**Comment by AndreasSko** [comment]
Thank you for reporting this issue!
Yeah, the update of JW Library changed a bit the layout of the backup. I'm currently working on updating Library Merger to accommodate the changes. Hopefully, you should see an update in the next few days. 
Thanks for your patience 🙂

**Comment by AndreasSko** [comment]
I released the update on the App Store yesterday, so that problem should be fixed now. Thanks again for reporting the issue and overall thank you for your patience 🙂
