### ISSUE TITLE
Schema version not compatible anymore

### ISSUE THREAD

**Issue by Smartis2812** [AndreasSko/ios-jwlm#60]
Hello,

since the 14.0.1 update of JWLibrary (the one with the playlists) the DB schema of *.jwlibrary is not compatible anymore with the Library Merger App.

Maybe you could look into it.

Thank you 🤗

**Comment by ferpavao** [comment]
Please, check #57 where this issue is addressed and the fix is on the way at #59.

**Comment by AndreasSko** [comment]
Yeah, that problem should be fixed now 🙂 Hopefully, merging works for you again with the latest version 😁
I would close this issue now. Thanks for reporting and for your patience overall 😊
