### ISSUE TITLE
Can’t find library app

### ISSUE THREAD

**Issue by sindybell101** [AndreasSko/ios-jwlm#61]
Hi,
This app no longer can find the JW Library app. Please help. 
Thank you.

**Comment by AndreasSko** [comment]
Hi, unfortunately I‘m not entirely sure what you mean with you can‘t find the JW Library App. I you‘ve received a „Schema version is incompatible“-error in the past: I released an update yesterday that should fix that problem 🙂 
I would close the issue for now, but feel free to comment again with some further explanation if your problem persists. Thanks 🙂
