### ISSUE TITLE
"schema version is too old" using JWL 14.0.2

### ISSUE THREAD

**Issue by sircharlo** [AndreasSko/ios-jwlm#66]
When opening a backup file from JWL 14.0.2 in Library Merger 0.7.2 (either from another device using AirDrop, or from the same device using the share sheet), I get the following error: 

`schema version is too old. Should be 14 is 13. You might need to upgrade to a newer version of JW Library first`

I think it might be a glitch in JWL to be frank, but I figured I'd report it nonetheless. 

Thanks for this great app!

**Comment by long-enan** [comment]
I also have the same problem. 😀

**Comment by Smartis2812** [comment]
I've the same issue in Library Merger 0.7.3 and JWL 14.0.2.

Thank you for looking into it 🤗

**Comment by Smartis2812** [comment]
> I've had success by using the go version and the [latest PR](https://github.com/AndreasSko/go-jwlm/pull/147) .

I'll check it out afterwards. Thank you

**Comment by sircharlo** [comment]
> I've the same issue in Library Merger 0.7.3 and JWL 14.0.2.
> 
> 
> 
> Thank you for looking into it 🤗

Being tracked in #68

**Comment by AndreasSko** [comment]
Thanks again for reporting the issue! I just submitted an update to the App Store which adds support for the new backup version. You should hopefully be able to download it within the next couple of days 👍😄

**Comment by long-enan** [comment]
Thank you Andreas. Well done. 🤗Warm Love EnanOn 1 Sep 2023, at 18:58, Andreas Skorczyk ***@***.***> wrote:﻿
Thanks again for reporting the issue! I just submitted an update to the App Store which adds support for the new backup version. You should hopefully be able to download it within the next couple of days 👍😄
