### ISSUE TITLE
Schema version too new

### ISSUE THREAD

**Issue by Klyntx** [AndreasSko/ios-jwlm#68]
Please see the following error that was returned:
“schema version is too new. Should be 13 is 14. Make sure you use the latest version of the merger”

Just a note - I am beyond excited to find your app! I have asked many if they knew of a way to accomplish what your app does. None knew of a way. I am looking forward to telling others that expressed how much they wish for a way to combine their backups too!  I have searched google many times looking (cautiously) for a way to go about this. Today, your app showed up at the top of my Google search results. 😊

**Comment by AndreasSko** [comment]
Thank you for reporting this issue and your kind words 🙂 
I just submitted an update to the App Store which adds support for the new backup version. You should hopefully be able to download it within the next couple of days 👍😄
