### ISSUE TITLE
Problems merging i get an error message

### ISSUE THREAD

**Issue by bpatinojw** [AndreasSko/ios-jwlm#69]
schema version is too new. Should be 13 is 14. Make sure you use the latest version of the merger

**Comment by sircharlo** [comment]
Duplicate of #68

**Comment by AndreasSko** [comment]
Thank you for reporting this issue. I just submitted an update to the App Store which adds support for the new backup version. You should hopefully be able to download it within the next couple of days 👍😄

**Comment by bpatinojw** [comment]
Thank you!


On Sep 1, 2023, at 12:56 PM, Andreas Skorczyk ***@***.***> wrote:


Thank you for reporting this issue. I just submitted an update to the App Store which adds support for the new backup version. You should hopefully be able to download it within the next couple of days 👍😄
