### ISSUE TITLE
Merger 0.7.4 crashes when trying to merge JWL 14.0.2 (316115) backups

### ISSUE THREAD

**Issue by sircharlo** [AndreasSko/ios-jwlm#74]
No error message, app just crashes. I enabled Sentry data collection, so hopefully you'll see it in the logs. I tried a few times, with and without playlists, but same result.

**Comment by sircharlo** [comment]
https://github.com/AndreasSko/ios-jwlm/assets/1275666/be16df78-d859-458e-95e5-edf7a84d4671

**Comment by AndreasSko** [comment]
Thank you for raising this issue! I already created a hot fix this morning (https://github.com/AndreasSko/ios-jwlm/pull/73), which is currently waiting for approval on the App Store. So hopefully that should be fixed in the next couple of hours/days 😊
