### ISSUE TITLE
Backup Not Compatible

### ISSUE THREAD

**Issue by Rhagel127** [AndreasSko/ios-jwlm#77]
Receiving the following error after updating both JW Library apps on iPhone and iPad and the MergeThe version of the backup you are trying to import is not supported anymore.
Make sure to export the backup using the latest version of JW Library and Library Merger app. Running iOS 17 Public Beta 6 and iPad OS 16.6.1. 

![IMG_3624](https://github.com/AndreasSko/ios-jwlm/assets/144544184/51f8fa22-a7f6-4aaf-85e7-202b5dab0f72)

**Comment by sircharlo** [comment]
If you're interested, I made a quick and dirty Python script to merge my backups while this app gets updated. 

Here it is:

https://github.com/sircharlo/jwl-backup-merger

**Comment by AndreasSko** [comment]
Thank you for opening this issue. As it was already mentioned in a separate issue, I would close this one for now. You can track the progress here: https://github.com/AndreasSko/ios-jwlm/issues/76#issuecomment-1712822064 😊
