### ISSUE TITLE
Backup not compatible 

### ISSUE THREAD

**Issue by bpatinojw** [AndreasSko/ios-jwlm#78]
![IMG_2309](https://github.com/AndreasSko/ios-jwlm/assets/143539140/db27c2c1-49b8-41f9-942d-4fb79e786990)

**Comment by sircharlo** [comment]
If you're interested, I made a quick and dirty Python script to merge my backups while this app gets updated. 

Here it is:

https://github.com/sircharlo/jwl-backup-merger

**Comment by AndreasSko** [comment]
Thank you for opening this issue. As it was already mentioned in a separate issue, I would close this one for now. You can track the progress here: https://github.com/AndreasSko/ios-jwlm/issues/76#issuecomment-1712822064 😊
